### ISSUE TITLE
FFMPEG error in HA startup

### ISSUE THREAD

**Issue by Hedgehog57** [fwestenberg/reolink#17]
Hello. Interesting component. I have started to write my own but Your is better than what I have done ATM.

Unfortunately, I have a problem with your code. Here is the error:

Error:
```
2019-12-12 20:41:30 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for reolink_dev which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-12 20:41:30 ERROR (MainThread) [homeassistant.components.camera] Error while setting up platform reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/config/custom_components/reolink_dev/camera.py", line 53, in async_setup_platform
    async_add_devices([ReolinkCamera(hass, config)], update_before_add=True)
  File "/config/custom_components/reolink_dev/camera.py", line 125, in __init__
    self._manager = self._hass.data[DATA_FFMPEG]
KeyError: 'ffmpeg'
```
Environment:
```
Raspberry PI 3B+
Raspbian 10.1
HASSIO 0.102.3 in docker
Reolink C2 
```
If You need more information - I am at Your service. ;)

**Comment by fwestenberg** [comment]
Just add `ffmpeg:` to your configuration.yaml, like described here:

https://www.home-assistant.io/integrations/ffmpeg/

Also, you can fork my project and work together!

**Comment by Hedgehog57** [comment]
I'm stupid. ;) Thanks a lot.
