### ISSUE TITLE
Support for D400

### ISSUE THREAD

**Issue by bjornta** [fwestenberg/reolink#25]
When trying to add a D400 with the same config as my working RLC-410-MP5, I get the following error messages when clicking the (broken) image in lovelace to open the stream, and then closing it:

2020-01-07 11:10:38 ERROR (stream_worker) [libav.tcp] Port missing in uri
2020-01-07 11:10:38 ERROR (stream_worker) [libav.rtmp] Cannot open connection tcp://192.168.50.40:0
2020-01-07 11:10:42 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 496, in get
    return await self.handle(request, camera)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 513, in handle
    image = await camera.async_camera_image()
  File "/home/homeassistant/.homeassistant/custom_components/reolink_dev/camera.py", line 244, in async_camera_image
    return self._reolinkSession.snapshot
  File "/home/homeassistant/.homeassistant/custom_components/reolink_dev/ReolinkPyPi/camera.py", line 127, in snapshot
    return response.content
AttributeError: 'NoneType' object has no attribute 'content'
-----------------------------------------------------------------------------------------------------------

I'm using similar config on all cameras:

- platform: reolink_dev
  host: 192.168.50.40
  username: !secret reolink_username
  password: !secret reolink_password
  name: Camera3
  stream: main
  protocol: rtmp
  channel: 0
  scan_interval: 5

I'm not using NVR, just registered the cameras in the app. All cameras works fine in the app.
The D400 does not have a web gui.

**Comment by fwestenberg** [comment]
Can you get an image as described here: https://support.reolink.com/hc/en-us/articles/360007011233-How-to-Capture-Live-JPEG-Image-of-Reolink-Cameras-via-Web-Browsers

**Comment by begicj** [comment]
As I know D400 is add-on camera and need to have NVR. 

![2065084F-AC8F-4C42-859A-8B7C54017781](https://user-images.githubusercontent.com/24259043/71896747-df349300-3154-11ea-8084-749c890921ab.jpeg)

**Comment by bjornta** [comment]
> Can you get an image as described here: https://support.reolink.com/hc/en-us/articles/360007011233-How-to-Capture-Live-JPEG-Image-of-Reolink-Cameras-via-Web-Browsers

No, I can't. Only through the app.

**Comment by bjornta** [comment]
> As I know D400 is add-on camera and need to have NVR.
> 
> ![2065084F-AC8F-4C42-859A-8B7C54017781](https://user-images.githubusercontent.com/24259043/71896747-df349300-3154-11ea-8084-749c890921ab.jpeg)

Yes, sort of. I can use the camera fine with the Reolink Android-app. I don't actually need the NVR to use it.

**Comment by bjornta** [comment]
I tried both rtmp and rtsp with VLC, but no luck getting the stream. I can't even get the still image using the same method as for the other cameras.

I was just gambling on this working, since I can use the app. It's a high quality, but very cheap camera. Probably cheap for a reason if it lacks a lot of functionality.
