### ISSUE TITLE
Can't use ir lights switch

### ISSUE THREAD

**Issue by Sjeff** [fwestenberg/reolink#32]
Hi,

Camera model : Reolink RLC-410W
Connected via Wifi

I receive this error when i enable/disable ir lights switch:

```
'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/template/switch.py", line 195, in async_turn_off
    await self._off_script.async_run(context=self._context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 247, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 331, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 101, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/reolink_dev/camera.py", line 123, in handler_disable_ir_lights
    entity.disable_ir_lights()
  File "/config/custom_components/reolink_dev/camera.py", line 278, in disable_ir_lights
    if self._reolinkSession.set_ir_lights(False):
  File "/config/custom_components/reolink_dev/ReolinkPyPi/camera.py", line 264, in set_ir_lights
    if json_data[0]["value"]["rspCode"] == 200:
KeyError: 'value'
```

template switch config :  
```
platform: template
switches:
  reolink_schuur_ir_lights:
    value_template: "{{ is_state_attr('camera.reolink_schuur_dev', 'ir_lights_enabled', true) }}"
    turn_on:
      service: camera.enable_ir_lights
      data:
        entity_id: camera.reolink_schuur_dev
    turn_off:
      service: camera.disable_ir_lights
      data:
        entity_id: camera.reolink_schuur_dev
    icon_template: >-
      {% if is_state_attr('camera.reolink_schuur_dev', 'ir_lights_enabled', true) %}
        mdi:flashlight
      {% else %}
        mdi:flashlight-off
      {% endif %}
```

best regards,
Sjeff

**Comment by fwestenberg** [comment]
Hi Sjeff,

Can you try in the browser what the request/response of switching the IR lights look like?

Thanks!

**Comment by Sjeff** [comment]
Hi @fwestenberg,

You mean the console?

![image](https://user-images.githubusercontent.com/11430228/80862714-7e871400-8c77-11ea-88da-e92c0ce60978.png)

**Comment by fwestenberg** [comment]
No just your browser. Go to the debugging and use the network tab. You should see something like this if you change the IR light and hit Save:
 
![image](https://user-images.githubusercontent.com/47930023/80925796-04e44880-8d93-11ea-8707-5e103d74e566.png)

**Comment by Sjeff** [comment]
Looks like this:
![image](https://user-images.githubusercontent.com/11430228/80943822-5f5bc400-8de8-11ea-826c-3da25f9c2f68.png)

**Comment by fwestenberg** [comment]
Strange, it should work. In your image you clearly see the key of the log:

`json_data[0]["value"]["rspCode"]` == 200`

Did you try the updated version by the way?

**Comment by Sjeff** [comment]
Running latest version installed via HACS. (d920cad)

**Comment by Sjeff** [comment]
Issue is fixed!
I was using a Guest user instead of an administrator.

When i switched to the administrator user i am able to turn on/off the ir light switch.

Also the motion sensor is working as expected.

**Comment by fwestenberg** [comment]
Thanks for your update!
