### ISSUE TITLE
After last update does not work anymore

### ISSUE THREAD

**Issue by KameDomotics** [fwestenberg/reolink#55]
This is error in the Log:

[    Logger: root
Source: components/stream/worker.py:49 
First occurred: 21:30:42 (2 occurrences) 
Last logged: 21:31:06

Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/thread.py", line 20, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 49, in stream_worker
    container = av.open(stream.source, options=stream.options)
  File "av/container/core.pyx", line 354, in av.container.core.open
  File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
  File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'rtsp://admin:xxxxxxxx@192.168.1.16:None/h264Preview_01_sub'; last error log: [tcp] Port missing in uri]()

**Comment by nick2k3** [comment]
Hi, can you post your  .yaml configuration?
Can you post your HA info?

**Comment by fwestenberg** [comment]
I will close this issue, as there is too less info provided. What camera do you have? Add your config and check if the camera ports are configured in the networking page of the camera. Probably RTSP is not configured well os something.
