### ISSUE TITLE
IR button doesn't work

### ISSUE THREAD

**Issue by badabing2005** [fwestenberg/reolink#68]
When clicking on the IR_Lights button, an error is displayed
Failed to call service/turn_on. 'value'

The HA logs show this
```
2020-09-04 15:30:47 ERROR (MainThread) [homeassistant.helpers.script] Error executing script. Unexpected error for call_service at pos 1: 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 191, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 380, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1347, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/reolink_dev/camera.py", line 116, in handler_enable_ir_lights
    entity.enable_ir_lights()
  File "/config/custom_components/reolink_dev/camera.py", line 323, in enable_ir_lights
    if asyncio.run_coroutine_threadsafe(self._reolinkSession.set_ir_lights(True), self.hass.loop).result():
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/config/custom_components/reolink_dev/ReolinkPyPi/camera.py", line 293, in set_ir_lights
    body = [{"cmd":"SetIrLights","action":0,"param": self._ir_settings["value"] }]
KeyError: 'value'
2020-09-04 15:30:47 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140524359648928] 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1343, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/template/switch.py", line 213, in async_turn_on
    await self._on_script.async_run(context=self._context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 802, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 183, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 191, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 380, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1308, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1347, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/reolink_dev/camera.py", line 116, in handler_enable_ir_lights
    entity.enable_ir_lights()
  File "/config/custom_components/reolink_dev/camera.py", line 323, in enable_ir_lights
    if asyncio.run_coroutine_threadsafe(self._reolinkSession.set_ir_lights(True), self.hass.loop).result():
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/config/custom_components/reolink_dev/ReolinkPyPi/camera.py", line 293, in set_ir_lights
    body = [{"cmd":"SetIrLights","action":0,"param": self._ir_settings["value"] }]
KeyError: 'value'
```

Developer Tools | States for the camera shows everything correctly except for the ir_lights_enabled which shows null
![image](https://user-images.githubusercontent.com/22603312/92279118-a7891100-eec4-11ea-8c7e-bfe1d0db2a30.png)

I double checked everything and I don't think I missed any step or had a typo, but if I did, I'm sure someone will let me know.
Thanks for integration.

BB

**Comment by thanpolas** [comment]
Same issue, I can't get any of the switches to work. My camera user is an admin. 

My HA Logs is empty though, how did you manage to log @badabing2005 ?

**Comment by badabing2005** [comment]
> Same issue, I can't get any of the switches to work. My camera user is an admin.
> 
> My HA Logs is empty though, how did you manage to log @badabing2005 ?

I didn't do anything special for logging, It gets logged anytime I press on the IR button

**Comment by badabing2005** [comment]
@thanpolas You can try the fix
https://github.com/badabing2005/reolink/pull/1

**Comment by badabing2005** [comment]
Closing the issue
