### ISSUE TITLE
Running alongside Blink integration

### ISSUE THREAD

**Issue by elyobelyob** [fwestenberg/reolink#7]
Hi,
I also run Blink cameras, but whenever I install the reolink custom integration I get the following error (TypeError: unhashable type: 'list') .... wondering if this is something that can be ironed out between the two integrations? Thanks

```
Blink's integration
    def enable_motion_detection(self):
        """Enable motion detection for the camera."""
        self._camera.set_motion_detect(True)

Reolink Integration
# Event enable motion detection
    def handler_enable_motion_detection(call):
        component = hass.data.get(DOMAIN)
        entity = component.get_entity(call.data.get(ATTR_ENTITY_ID))

        if entity:
            entity.enable_motion_detection()
    hass.services.async_register(DOMAIN, SERVICE_ENABLE_MOTION_DETECTION, handler_enable_motion_detection)
```

---- 
Error log : 

`2020-11-26 20:39:43 INFO (MainThread) [homeassistant.components.automation.cameras_on] Cameras On: Executing step call service
2020-11-26 20:39:43 ERROR (MainThread) [homeassistant.components.automation.cameras_on] Cameras On: Error executing script. Unexpected error for call_service at pos 1: unhashable type: 'list'
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1490, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/homeassistant/custom_components/reolink_dev/camera.py", line 149, in handler_enable_motion_detection
    entity = component.get_entity(call.data.get(ATTR_ENTITY_ID))
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 99, in get_entity
    entity_obj = platform.entities.get(entity_id)
TypeError: unhashable type: 'list'
2020-11-26 20:39:43 ERROR (MainThread) [homeassistant.components.automation.cameras_on] While executing automation automation.cameras_on
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/automation/__init__.py", line 433, in async_trigger
    await self.action_script.async_run(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 1010, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 245, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 253, in _async_step
    await getattr(
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/script.py", line 460, in _async_call_service_step
    await service_task
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1451, in async_call
    task.result()
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 1490, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/homeassistant/custom_components/reolink_dev/camera.py", line 149, in handler_enable_motion_detection
    entity = component.get_entity(call.data.get(ATTR_ENTITY_ID))
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 99, in get_entity
    entity_obj = platform.entities.get(entity_id)
TypeError: unhashable type: 'list'`

**Comment by fwestenberg** [comment]
Hi there! I recently moved the reolink library to https://github.com/fwestenberg/reolink_dev, because this will become the official HA library (pull request is pending ;-) ). Your issue clearly comes from the old library, mentioned above. Please wait, or manually install the new library to your custom components like I described here: https://github.com/home-assistant/core/pull/43195#issuecomment-733188595
Please post your findings about the new integration only here. Thanks!

**Comment by elyobelyob** [comment]
Fair enough, will wait! Happy to test then! Please do let the watchers know
when it goes live .. good luck!
